### ISSUE TITLE
Question about  OmniRL project

### ISSUE THREAD

**Issue by SharingChen** [airs-cuhk/airsoul#22]
我尝试用开源的配置文件和训练好的模型参数文件 运行generate.py, 但是无法得到预期的结果.
配置文件: config_16-128state_stage2_gsa_l32k_t512k_hot.yaml
模型参数文件: model.pth

Q1: 配置文件名为 stage2   是否模型参数也是stage2 训练后的结果,而不是stage3.
Q2: 配置文件中关于action_decode的配置,最终输出维度是否应该是5. 而且该配置文件在使用中缺少一些关键参数配置,例如'agent_num'.
```
  action_decode:
      output_type: Discrete
      input_size: 512
      hidden_size:
          - 512
          - 6
      layer_norm: True
      residual_connect: True
      dropout: 0.0
      is_frozen: False
```
能否更新配置文件和训练好的模型参数, 能够直接运行generate.py文件,以'lake4x4'环境配置为例,可以得到文章中的预期实验结果,感谢!
